server:
  port: 8081

spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/sgc_telecom
    username: root
    password: admin2006
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true